MODEL:
  TYPE: vssm_efficient
  NAME: vssm_efficient
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 4, 2]
    D_STATE: 16
    DT_RANK: "auto"
    SSM_RATIO: 2.0
    MLP_RATIO: 0.0
    DOWNSAMPLE: "v1"
    WINDOWSIZE: 2